[package]
name = "host"
version = "0.1.0"
edition = "2021"

[dependencies]
methods = { path = "../methods" }
risc0-zkvm = { version = "=0.19.1", features = ["prove"] }
serde = "1.0"
rand_chacha = "0.3.1"
raki = "0.1.3"
colored = "2.0.4"